/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package act3;

/**
 *
 * @author Salvador
 */
public class Act3 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        int [] vect = {4,15,63,13,35,24,11,9}; //Test array
        Secuencial sec = new Secuencial();
        sec.setV(vect);
        //sec.setV(10); //A random array can be generated by inputting an array size instead of a predefined vector.
        sec.showV();
        System.out.println();
        sec.showF(sec.Search(13));
        //Using a binary search requires the array to be in order, hence the use of ordering algorithms
        Binaria bin = new Binaria();
        bin.setV(vect);
        //bin.setV(10); //A random array can be generated by inputting an array size instead of a predefined vector.
        //Test ordering methods to order the array
        /*
        bin.selection();
        bin.bubble();
        bin.insertion();
        bin.mergeSort(0, bin.vector.length-1);
        bin.quickSort(0, bin.vector.length-1);
        */
        //Search of the value
        int b = bin.Search(35);
        //Print of results and array
        bin.showV();        
        bin.showF(b);
    }
    
}
